# .github/dependabot.yml
version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"             # Path to pom.xml
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    groups:
      all-deps:
        patterns:
          - "*"                # Group *all* dependency updates into one PR
