version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1  # Limit to one PR
    assignees:
      - "qStivi"
    reviewers:
      - "qStivi"
    labels:
      - "dependencies"
    commit-message:
      prefix: "deps"
    pull-request-branch-name:
      separator: "-"
    versioning-strategy: increase
    groups:
      dependencies:
        patterns:
          - "*"  # Groups all dependencies into one PR
