name: Build and Deploy

on:
  push:
    branches:
      - master  # Ensure this matches your branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '22'

      - name: Build with Maven
        run: mvn clean package

      - name: Get short commit SHA
        run: echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Create release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ env.short_sha }}
          name: Release ${{ env.short_sha }}
          draft: false
          prerelease: false
          body: "Automated release of version ${{ env.short_sha }}"

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: target/MusicBot-1.jar
          asset_name: qMusic.jar
          asset_content_type: application/java-archive
