# .github/workflows/build-and-deploy.yml
name: Build and Deploy

on:
  push:
    branches: [ master, main ]        # Trigger on pushes to the main branch
  pull_request:
    types: [ closed ]        # Trigger when a PR is merged (closed with merge)

jobs:
  build:
    # Only run on merges or direct pushes (avoid duplicate run on PR close without merge)
    if: ${{ github.event.pull_request == null || github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '22'

      - name: Build with Maven
        run: mvn clean package

      - name: List target directory
        run: ls -lh target

      - name: Rename jar for release
        run: mv target/qMusic-jar-with-dependencies.jar target/qMusic.jar

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: auto-release-${{ github.run_id }}
          name: "Automated Release ${{ github.run_id }}"
          draft: false
          prerelease: false
          generateReleaseNotes: true
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: target/qMusic.jar

