name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '22'

      - name: Build with Maven
        run: mvn clean package

      - name: Get date and time for version
        id: get_datetime
        run: |
          datetime=$(date +'%Y-%m-%d_%H-%M')
          echo "datetime=$datetime" >> $GITHUB_ENV

      - name: Create release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: auto-release-${{ env.datetime }}
          name: "Automated Release ${{ env.datetime }}"
          draft: false
          prerelease: false
          body: "Automated release generated on ${{ env.datetime }}"
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          generateReleaseNotes: true
      
      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: target/MusicBot-1.jar
          asset_name: qMusic.jar
          asset_content_type: application/java-archive
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
