name: Build and Deploy

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - closed  # Triggers build when a PR is merged

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '22'

      - name: Build with Maven
        run: mvn clean package

      - name: Send Discord notification (build started)
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: "🛠️ Build started for qMusic..."

      - name: Send Discord notification (build success)
        if: success()
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: "✅ Build successful! New release incoming..."

      - name: Send Discord notification (build failed)
        if: failure()
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: "❌ Build failed! Check logs: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"

      - name: Create release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: auto-release-${{ github.run_id }}
          name: "Automated Release ${{ github.run_id }}"
          draft: false
          prerelease: false
          body: "Automated release generated from CI build."
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          generateReleaseNotes: true

      - name: Send Discord notification (release created)
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: "🚀 New release: [Build ${{ github.run_id }}](${{ github.server_url }}/${{ github.repository }}/releases/tag/auto-release-${{ github.run_id }})"

#      - name: Send email notification if build fails
#        if: failure()
#        uses: dawidd6/action-send-mail@v3
#        with:
#          server_address: smtp.example.com
#          server_port: 587
#          username: ${{ secrets.EMAIL_USER }}
#          password: ${{ secrets.EMAIL_PASS }}
#          subject: "🚨 Build Failed: qMusic"
#          body: "The latest build of qMusic failed. Check logs at ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
#          to: "your-email@example.com"
#          from: "github-actions@example.com"
