name: Post-Build Notification

on:
  workflow_run:
    workflows: ["Build and Deploy"]
    types:
      - completed

jobs:
  notify:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord notification (post-merge)
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: "🎉 Successfully deployed! Triggered by ${{ github.event.workflow_run.head_commit.author.name }}.\nSee: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}"
